### ISSUE TITLE
RabbitMQ and Docker

### ISSUE THREAD

**Issue by almereyda** [kanboard/plugin-rabbitmq#3]
When using this plugin with the official Kanboard Docker distribution, the process throws an error similar to:

```
app_1       | 2018/12/07 17:56:13 [error] 16#16: *102 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function PhpAmqpLib\Wire\bcadd() in /var/www/app/plugins/RabbitMQ/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPWriter.php:274
app_1       | Stack trace:
app_1       | #0 /var/www/app/plugins/RabbitMQ/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(412): PhpAmqpLib\Wire\AMQPWriter->write_longlong(68)
app_1       | #1 /var/www/app/plugins/RabbitMQ/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(367): PhpAmqpLib\Connection\AbstractConnection->prepare_content(1, 60, 0, 68, '\x80\x00\ntext/plain', '{"class":"Kanbo...', Object(PhpAmqpLib\Wire\AMQPWriter))
app_1       | #2 /var/www/app/plugins/RabbitMQ/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(1111): PhpAmqpLib\Connection\AbstractConnection->send_content(1, 60, 0, 68, '\x80\x00\ntext/plain','{"class":"Kanbo...', Object(PhpAmqpLib\Wire\AMQPWriter))
app_1       | #3 /var/www/app/libs/SimpleQueue/Adapter/AmqpQueueAdapter.php(58): PhpAmqpLib\Channel\AMQPChannel->basic_publish(Object(Ph" while reading response header from upstream, client: 172.19.0.2, server: localhost, request: "POST /?controller=BoardAjaxController&action=save&project_id=6 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "kanban.allmende.io"
```

This is due to the [`php7-bcmath`](https://pkgs.alpinelinux.org/package/v3.8/community/x86_64/php7-bcmath) extension missing from the base image.

https://github.com/kanboard/kanboard/blob/master/Dockerfile#L12-L15

**Comment by almereyda** [comment]
I have filed a corresponding PR upstream with a suggested patch at https://github.com/kanboard/kanboard/pull/4094

**Comment by almereyda** [comment]
This was merged, thanks.
